### ISSUE TITLE
关于游戏内经验仓库刷经验的问题

### ISSUE THREAD

**Issue by Nanaloveyuki** [ChongYuCN/DangerousWorld#1]
### 问题描述
经验仓库在存有经验时快速点击存入(任意数值)和取出(任意数值)时会存在刷经验/吃经验bug
![image](https://github.com/ChongYuCN/DangerousWorld/assets/136328617/48453b96-04e7-44db-9d46-4bf7241a062f)

### 问题版本/配置信息
Fabric 1.20.1 0.14.22
Fabric-api-0.90.7+1.20.1
Mem 9600MB
Java21 - Zulu
Windows 11 23h2

危险世界本体Mod:
3.1.10 + 1.20.1Fab

### 问题过程
在游玩危险世界(1.20.1)时使用仓库时无意间快速点击了多次存入和取出, 而后再取出经验发现经验由10级变为41级. 
随后我意识到这是个恶性bug, 随即来Iss一下

在测试此bug时我发现, 使用外置作弊(连点器或滑轮速点)成功几率很高, 此bug不仅可以刷经验也可以吞经验
如果作者要测试此bug可以使用鼠大侠一类的软件连点器测试, 成功几率很高

**Comment by ChongYu668** [comment]
确实有这个问题，感谢反馈

**Comment by Nanaloveyuki** [comment]
感谢作者关注此问题
