### ISSUE TITLE
[非重要]是否可将JEI更换成JEI+EMI

### ISSUE THREAD

**Issue by Nanaloveyuki** [ChongYuCN/DangerousWorld#2]
### 问题描述
在后期时JEI这种经典物品管理器对于后期AE/机械动力等mod配方兼容性不是很好,是否可换成EMI

### 理由
1. 在后期时JEI这种经典物品管理器对于AE/机械动力等mod配方兼容性不是很好

2. EMI作为高版本的新型物品管理器, 基本兼容了JEI(可以覆盖运行, 无需剔除JEI)

3. 对于AE类的mod也有单独的扩展mod增加显示配方
  - [_AE-EMI_](https://modrinth.com/mod/ae2-emi-crafting)

4. 在舒适度方面和原版兼容性方面都领先于JEI

5. 兼容性方面已经做了测试, 目前所有Modrinth的EMI都可兼容此版本并稳定运行
![image](https://github.com/ChongYuCN/DangerousWorld/assets/136328617/bdca2645-25b3-4837-ae33-111430747392)

### 为什么要用Iss的方式提交
请求作者意见而并非是提交意见

**Comment by ChongYu668** [comment]
emi有秒合成功能，不适合该整合包。

**Comment by Nanaloveyuki** [comment]
ok了解, 那么再麻烦问一下EMI是否有提供禁用单项配置功能?

**Comment by ChongYu668** [comment]
emi功能有很多，我只知道可以不用工作台秒合成，还有配置指定物品是否显示
