### ISSUE TITLE
关于FTB任务的历史遗留问题

### ISSUE THREAD

**Issue by Nanaloveyuki** [ChongYuCN/DangerousWorld#3]
### 问题描述
翻阅整合包文件时发现了FTBq的任务列表,打开看了一下发现有很多弃坑内容但在3.1.10中并未添加,因此需要删除
例如:
1. 暮色森林
2. 生存线
etc...

![image](https://github.com/ChongYuCN/DangerousWorld/assets/136328617/a39c02b9-4e20-4b4f-a965-c311dc3bcf6e)
 
![image](https://github.com/ChongYuCN/DangerousWorld/assets/136328617/e43d876a-9a2d-4fb1-a1d0-8ce9c2dee601)

![image](https://github.com/ChongYuCN/DangerousWorld/assets/136328617/8ac746c7-e9bb-44dd-a023-649de77f566a)

**Comment by ChongYu668** [comment]
1.20我已经交给别人续写了，后续会重新写任务指引

**Comment by Nanaloveyuki** [comment]
好的,谢谢回复
